apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app 
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-multitool
        image: wbitt/network-multitool
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3452
        env:
          - name: "HTTP_PORT"
            value: "3452"

      # - name: cache-nginx
      #   image: nginx:1.14.2
      #   # resources:
      #   #   limits:
      #   #     memory: "128Mi"
      #   #     cpu: "500m"
      #   ports:
      #   - containerPort: 80
      #   env:
      #     - name: "HTTP_PORT"
      #       value: "80"